In [1]:
# pytorch tensor

In [2]:
# Broadcasting
# 사이즈가 다른 tensor의 연산을 진행할때 pytorch에서 자동으로 제공
# 자동으로 적용되기 때문에 주의해서 사용해야됨.

import torch

m1 = torch.FloatTensor([[3, 3]])
m2 = torch.FloatTensor([[2, 2]])
print(m1 + m2)

tensor([[5., 5.]])


In [4]:
# Vector + scalar
m1 = torch.FloatTensor([[3, 3]])
print(m1.shape)
m2 = torch.FloatTensor([3])
print(m2.shape)
print(m1 + m2)

torch.Size([1, 2])
torch.Size([1])
tensor([[6., 6.]])


In [5]:
# 2 x 1 vertor + 1 x 2 vector
m1 = torch.FloatTensor([[1, 2]])
print(m1.shape)
m2 = torch.FloatTensor([[3], [4]])
print(m2.shape)
m3 = m1 + m2
print(m3.shape)
print(m3)

torch.Size([1, 2])
torch.Size([2, 1])
torch.Size([2, 2])
tensor([[4., 5.],
        [5., 6.]])


In [7]:
# View (reshape in numpy)
# 각 tensor shape를 곱한건 결국 동일함
# 2 * 2 * 3 == 4 * 3 == 4 * 1 * 3
import numpy as np
t = np.array([[[0, 1, 2],
               [3, 4, 5]],
              [[6, 7, 8],
               [9, 10, 11]]])

ft = torch.FloatTensor(t)
ft.shape

torch.Size([2, 2, 3])

In [10]:
print(ft.view([-1, 3]))
print(ft.view([-1, 3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [11]:
ft.view([-1, 1, 3])

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])

In [12]:
ft.view([-1, 1, 3]).shape

torch.Size([4, 1, 3])

In [13]:
# Squeeze
# view와 동일한데 dimension의 element의 개수가 1인 경우에 없애줌
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [14]:
ft.squeeze()

tensor([0., 1., 2.])

In [15]:
ft.squeeze().shape

torch.Size([3])

In [16]:
# unsqueeze
ft = torch.Tensor([0, 1, 2])
ft.shape

torch.Size([3])

In [18]:
print(ft.unsqueeze(dim=0))
print(ft.unsqueeze(dim=0).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [22]:
t = torch.Tensor([0])

In [23]:
t.shape

torch.Size([1])